export default [
    {state : false, letter: 'q'},
    {state : false, letter: 'w'},
    {state : false, letter: 'e'},
    {state : false, letter: 'r'},
    {state : false, letter: 't'},
    {state : false, letter: 'y'},
    {state : false, letter: 'u'},
    {state : false, letter: 'i'},
    {state : false, letter: 'o'},
    {state : false, letter: 'p'},
    {state : false, letter: 'a'},
    {state : false, letter: 's'},
    {state : false, letter: 'd'},
    {state : false, letter: 'f'},
    {state : false, letter: 'g'},
    {state : false, letter: 'h'},
    {state : false, letter: 'j'},
    {state : false, letter: 'k'},
    {state : false, letter: 'l'},
    {state : false, letter: 'z'},
    {state : false, letter: 'x'},
    {state : false, letter: 'c'},
    {state : false, letter: 'v'},
    {state : false, letter: 'b'},
    {state : false, letter: 'n'},
    {state : false, letter: 'm'}
]