export default [
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `1`,
        name: `asd1`,
        lvl: `5`,
        price: `100`,
    },
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `2`,
        name: `asd2`,
        lvl: `5`,
        price: `100`,
    },
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `3`,
        name: `asd3`,
        lvl: `8`,
        price: `250`,
    },
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `4`,
        name: `asd4`,
        lvl: `8`,
        price: `300`,
    },
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `5`,
        name: `asd5`,
        lvl: `10`,
        price: `1000`,
    },
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `6`,
        name: `asd6 asder`,
        lvl: `10`,
        price: `2000`,
    },
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `7`,
        name: `bdavd`,
        lvl: `69`,
        price: `420`,
    },
    {
        image:require(`../../assets/hangtree-skins/placeholder.png`),
        key: `8`,
        name: `megasd`,
        lvl: `1`,
        price: `50`,
    },
]